name: Build and publish docker images

# do this on branches and merges
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        uses: docker/build-push-action@v1.1.0

      - name: Publish Docker Image to Github packages
        uses: matootie/github-docker@v3.0.0        
        with:
          accessToken: ${{ github.token }}
          imageName: docker.pkg.github.com/sacasumo/docker-diagrams:v0.1
