name: Build and publish docker images

# do this on branches and merges
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        uses: docker/build-push-action@v1.1.0

      - name: Publish Docker Image to Github packages
        uses: matootie/github-docker@v3.0.0
        id: publish
        with:
          accessToken: ${{ github.token }}
          imageName: docker.pkg.github.com/sacasumo/docker-diagrams 
          tag: |
            latest
            ${{ github.sha }}
            v0.1

      - name: Print Image URL
        run: echo ${{ steps.publish.outputs.imageURL }}:${{ github.sha }}